version: '3'
services:
  default:
    image: weli/docker-hibernate-build:latest
#    restart:
#    volumes:
#      - /tmp:/tmp
#    environment:
#      DB_HOST: localhost
#      DB_USER: foo
#      DB_PASSWORD:
    command: /var/run/postinstall.sh
    ports:
      - 5432:5432
      - 22
